services:
  db_v2:
    image: postgres:15-alpine
    container_name: pac-db-v2
    environment:
      POSTGRES_DB: pac_mcmv_v2
      POSTGRES_PASSWORD: V2secret
    ports: ["55432:5432"]

  etl_v2:
    image: python:3.11-slim          # ← no Dockerfile needed
    container_name: pac-etl-v2
    command: ["sleep", "infinity"]   # placeholder so the container just stays up
    environment:
      DB_URL: postgresql://postgres:V2secret@db_v2:5432/pac_mcmv_v2
    depends_on: [db_v2]

  dashboard_v2:
    image: python:3.11-slim          # ← no Dockerfile needed
    container_name: pac-dash-v2
    command: >
      bash -c "pip install streamlit &&
               streamlit run /app/app.py"
    volumes:
      - ./dashboards/streamlit:/app  # mount our hello-world app
    ports: ["8503:8501"]
    depends_on: [db_v2]

