version: "3.9"
services:
  db_v2:
    image: postgres:15-alpine
    container_name: pac-db-v2
    environment:
      POSTGRES_DB: pac_mcmv_v2
      POSTGRES_PASSWORD: V2secret
    ports: ["55432:5432"]
    volumes:
      - db_data_v2:/var/lib/postgresql/data

  etl_v2:
    build: ./etl
    container_name: pac-etl-v2
    environment:
      DB_URL: postgresql://postgres:V2secret@db_v2:5432/pac_mcmv_v2
    depends_on: [db_v2]
    volumes:
      - ./sample_data:/data:ro

  dashboard_v2:
    build: ./dashboards/streamlit
    container_name: pac-dash-v2
    environment:
      DB_URL: postgresql://postgres:V2secret@db_v2:5432/pac_mcmv_v2
    ports: ["8503:8501"]
    depends_on: [db_v2]
volumes:
  db_data_v2:
